version: '3.7'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  registry-data:
    driver: glusterfs
    driver_opts:
      voluri: "localhost:/gv0"
